version: '3'
services:
  myapp-prod:
      image: nginx    
      volumes:
            - ./webroot:/usr/share/nginx/html    
      ports:      
            - "9090:80"    
      restart: unless-stopped